chore:(demo-playwright): implement input card grouped tests
taiga-family/taiga-ui pull request #5624
Opened 2023-10-13 03:05 UTC by aotulana

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [X] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Addresses #4912 

## What is the new behaviour?
This PR adds playwright e2e test for input card grouped and removes the corresponding cypress tests

2023-10-13 07:29 UTC, nsbarsukov requested changes

2023-10-13 07:29 UTC, nsbarsukov commented on projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts
> +        .locator(`[automation-id="tui-toggle__checkbox"]`);
This method to disable component is just legacy way (when API pages did not support query param for `disable`).
Now we can just add it to url:
https://taiga-ui.dev/components/input-card-grouped/API?disabled=true

```ts
await tuiGoto(page, `components/input-card-grouped/API?disabled=true`);
```

____

Delete this property from `TuiInputCardGroupedPO` and update tests, please

2023-10-13 07:29 UTC, nsbarsukov commented on projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts
> +    getExampleCardExpiryInput(example: Locator): Locator {
Page objects should know nothing about "external environment".

Drop all mentions about `example`

2023-10-13 07:29 UTC, nsbarsukov commented on projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts
> +    constructor(private readonly page: Page) {}
See other PO examples and make `TuiInputCardGroupedPO` to be similar to them

https://github.com/taiga-family/taiga-ui/blob/0e61adf8a57b87415879792cd856b65531c265e0/projects/demo-playwright/utils/page-objects/input-date-range.po.ts#L7

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts
> +    readonly cardCvcInput = this.host.locator(
All other PO uses term "textfield".
Let's rename `input` and drop prefix `card`:

```suggestion
    readonly numberTextfield = this.host.locator(
        `[automation-id="tui-input-card-grouped__card"]`,
    );

    readonly cleanerIcon = this.host.locator(
        `[automation-id="tui-input-card-grouped__cleaner"]`,
    );

    readonly expiryTextfield = this.host.locator(
        `[automation-id="tui-input-card-grouped__expire"]`,
    );

    readonly cvcTextfield = this.host.locator(
```

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/utils/page-objects/input-card.po.ts
> +    readonly cardExpiryInput = this.host
```suggestion
    readonly expiryTextfield = this.host
```

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts
> +        inputCardPage = new TuiInputCardPO(example);
```suggestion
        inputCard = new TuiInputCardPO(example);
```

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts
> +    readonly cardCvcInput = this.host.locator(
Usage example:
```ts
const inputCard = new TuiInputCardPO(example);

await inputCard.expiryTextfield.pressSequentially('123');
await expect(inputCard.expiryTextfield).toHaveValue('123');
```

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts
> +        example = documentationPage.apiPageExample;
```suggestion
       const {apiPageExample} = new TuiDocumentationPagePO(page);
```

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts
> +    let expectedValue: string;
Why do we need to share these variables between tests ? 🤔

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-card-grouped.spec.ts
> +    use({viewport: {width: 1280, height: 800}});
Let use
```ts
use({viewport: {width: 700, height: 800}});
```

for `describe('API')`

___

And use

```ts
use({viewport: {width: 1280, height: 800}});
```

for `describe('Examples')`

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts
> +    let expectedValue: string;
The only variable you actually use between all tests is `cardExpiryInput`.

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-card-grouped.spec.ts
> +            example = documentationPage.getExample(`#validation`);
No need to "share" variable as you create this variable in every test.

```suggestion
            const example = documentationPage.getExample(`#validation`);
```

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-card-grouped.spec.ts
> +            example = documentationPage.getExample(`#validation`);
(the same for other variables)

2023-10-19 12:33 UTC, nsbarsukov commented on projects/demo-playwright/tests/addon-commerce/input-card-grouped.spec.ts
> +            inputCardGroupedPage = new TuiInputCardGroupedPO(example);
```suggestion
            inputCardGrouped = new TuiInputCardGroupedPO(example);
```

2023-10-20 08:37 UTC, vladimirpotekhin approved these changes

2023-10-20 08:38 UTC, splincode approved these changes

2023-10-20 08:38 UTC, splincode approved these changes

2023-10-20 08:42 UTC, merged