chore(demo): set related page as standalone
taiga-family/taiga-ui pull request #6571
Opened 2024-01-26 15:11 UTC by splincode

2024-01-31 10:46 UTC, vladimirpotekhin approved these changes

2024-02-02 13:12 UTC, nsbarsukov requested changes

2024-02-02 14:30 UTC, splincode commented on projects/demo/src/modules/info/related/related.component.ts
> +    imports: [TuiDocPageModule, TuiIslandModule],
fixed

2024-02-05 07:58 UTC, nsbarsukov approved these changes

2024-02-05 08:32 UTC, merged