chore: drop `MyModule` in md files
taiga-family/taiga-ui pull request #7312
Opened 2024-04-24 13:50 UTC by splincode

2024-04-24 14:11 UTC, nsbarsukov requested changes

2024-04-24 14:11 UTC, nsbarsukov commented on projects/demo/src/modules/components/avatar/examples/import/import.md
<img width="1488" alt="Снимок экрана 2024-04-24 в 17 10 59" src="https://github.com/taiga-family/taiga-ui/assets/35179038/2235baca-6aea-4a50-a392-0a292c05f55c">

2024-04-24 14:15 UTC, splincode commented on projects/demo/src/modules/components/avatar/examples/import/import.md
fixed

2024-04-26 09:25 UTC, nsbarsukov commented on projects/demo/src/modules/components/input-number/examples/import/import-module.md
`MyComponentModule`

2024-04-26 09:25 UTC, nsbarsukov commented on projects/demo/src/modules/components/range/examples/import/import-module.md
> +@Component({
`ExampleModule`

2024-04-26 09:25 UTC, nsbarsukov commented on projects/demo/src/modules/components/tag/examples/import/import-module.md
>      imports: [
line break

2024-04-26 09:25 UTC, nsbarsukov commented on projects/demo/src/modules/services/table-bar/examples/import/module.md
> +export class MyComponent {}
`export class App {}`

2024-04-26 09:25 UTC, nsbarsukov commented on projects/demo/src/modules/services/table-bar/examples/import/service-usage.md
> +export class MyComponent {
```suggestion
export class App {
```

2024-04-26 09:25 UTC, nsbarsukov commented on projects/i18n/README.md
> +export class MyComponent {}
`App`

2024-04-26 09:25 UTC, nsbarsukov commented on projects/i18n/README.md
> +export class MyComponent {}
`App`

2024-05-03 14:55 UTC, splincode commented on projects/i18n/README.md
> +export class MyComponent {}
fixed

2024-05-03 14:55 UTC, splincode commented on projects/i18n/README.md
> +export class MyComponent {}
fixed

2024-05-03 14:56 UTC, splincode commented on projects/demo/src/modules/services/table-bar/examples/import/service-usage.md
> +export class MyComponent {
fixed

2024-05-03 14:56 UTC, splincode commented on projects/demo/src/modules/services/table-bar/examples/import/module.md
> +export class MyComponent {}
fixed

2024-05-03 14:56 UTC, splincode commented on projects/demo/src/modules/components/tag/examples/import/import-module.md
>      imports: [
fixed

2024-05-03 14:56 UTC, splincode commented on projects/demo/src/modules/components/range/examples/import/import-module.md
> +@Component({
fixed

2024-05-03 14:56 UTC, splincode commented on projects/demo/src/modules/components/input-number/examples/import/import-module.md
fixed

2024-05-06 07:26 UTC, vladimirpotekhin approved these changes

2024-05-07 09:30 UTC, nsbarsukov approved these changes

2024-05-07 09:34 UTC, merged