chore(demo): markup section as standalone
taiga-family/taiga-ui pull request #7497
Opened 2024-05-20 11:56 UTC by splincode

2024-05-20 15:58 UTC, waterplea approved these changes

2024-05-21 07:40 UTC, nsbarsukov commented on projects/demo/src/modules/components/island/examples/1/index.ts
> +    imports: [TuiIslandModule, TuiLinkDirective],
![image](https://github.com/taiga-family/taiga-ui/assets/35179038/a991688c-2e93-4284-8ddd-4a6ff73629f5)



https://taiga-ui--pr7497-splincode-markup-rr0ywop3.web.app/components/island#base

2024-05-21 07:42 UTC, nsbarsukov commented on projects/demo/src/modules/markup/breakpoints/index.html
> +            [content]="1 | tuiExample"
<img width="1484" alt="Снимок экрана 2024-05-21 в 10 41 47" src="https://github.com/taiga-family/taiga-ui/assets/35179038/02a47528-e65b-4893-9560-ee8703656710">

https://taiga-ui--pr7497-splincode-markup-rr0ywop3.web.app/breakpoints

2024-05-21 07:43 UTC, nsbarsukov commented on projects/demo/src/modules/markup/colors/examples/table/table.style.less
> +@import '../../../../../../../../node_modules/@taiga-ui/core/styles/taiga-ui-local';
🤔

2024-05-21 07:43 UTC, nsbarsukov commented on projects/demo/src/modules/markup/colors/examples/table/table.style.less
> +@import '../../../../../../../../node_modules/@taiga-ui/core/styles/taiga-ui-local';
🤔

2024-05-21 07:44 UTC, nsbarsukov commented on projects/demo/src/modules/markup/form/index.html
> +            [content]="1 | tuiExample"
<img width="1484" alt="Снимок экрана 2024-05-21 в 10 44 24" src="https://github.com/taiga-family/taiga-ui/assets/35179038/f650102d-8aba-4413-a226-d5743bc3e102">

https://taiga-ui--pr7497-splincode-markup-rr0ywop3.web.app/form

2024-05-21 07:47 UTC, nsbarsukov commented on projects/demo/src/modules/markup/spaces/index.html
> +            [content]="1 | tuiExample"
<img width="1484" alt="Снимок экрана 2024-05-21 в 10 47 12" src="https://github.com/taiga-family/taiga-ui/assets/35179038/0073c10c-6916-4fcf-942a-8178c366720a">

https://taiga-ui--pr7497-splincode-markup-rr0ywop3.web.app/spaces

2024-05-21 07:48 UTC, nsbarsukov requested changes

2024-05-21 07:48 UTC, nsbarsukov commented on projects/demo/src/modules/markup/tables/index.ts
Run demo application locally and double check ALL changed pages, please

2024-05-21 07:49 UTC, nsbarsukov commented on projects/demo/src/modules/markup/tables/index.ts
<img width="1484" alt="Снимок экрана 2024-05-21 в 10 49 03" src="https://github.com/taiga-family/taiga-ui/assets/35179038/8af3f58a-7f11-47f3-ad1c-082849d28bef">

https://taiga-ui--pr7497-splincode-markup-rr0ywop3.web.app/tables

2024-05-21 08:23 UTC, splincode commented on projects/demo/src/modules/components/island/examples/1/index.ts
> +    imports: [TuiIslandModule, TuiLinkDirective],
fixed

2024-05-21 08:24 UTC, splincode commented on projects/demo/src/modules/markup/breakpoints/index.html
> +            [content]="1 | tuiExample"
fixed

2024-05-21 08:24 UTC, splincode commented on projects/demo/src/modules/markup/colors/examples/table/table.style.less
> +@import '../../../../../../../../node_modules/@taiga-ui/core/styles/taiga-ui-local';
fixed

2024-05-21 08:24 UTC, splincode commented on projects/demo/src/modules/markup/lists/index.html
> +        [content]="1 | tuiExample: 'ts'"
fixed

2024-05-21 08:24 UTC, splincode commented on projects/demo/src/modules/markup/spaces/index.html
> +            [content]="1 | tuiExample"
fixed

2024-05-21 08:24 UTC, splincode commented on projects/demo/src/modules/markup/tables/index.ts
fixed

2024-05-21 14:10 UTC, nsbarsukov commented on projects/demo/src/modules/markup/form/examples/1/index.less
> +@import '../../../../../../../../node_modules/@taiga-ui/core/styles/taiga-ui-local';
Should we revert this line ?

2024-05-21 14:13 UTC, nsbarsukov approved these changes

2024-05-21 18:51 UTC, merged