chore: remove redundant line
taiga-family/taiga-ui pull request #9195
Opened 2024-09-25 13:50 UTC by splincode

2024-09-27 08:37 UTC, vladimirpotekhin approved these changes

2024-09-27 11:38 UTC, nsbarsukov requested changes

2024-09-27 11:38 UTC, nsbarsukov commented on projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
> -    tuiAssetsPathProvider('https://taiga-ui.dev/next/assets/taiga-ui/icons'),
https://taiga-ui.dev/next/components/avatar#content-types

<img width="435" alt="before-stackblitz" src="https://github.com/user-attachments/assets/50389e19-747a-4f49-9078-8c51dcdd1544">

2024-09-27 11:38 UTC, nsbarsukov commented on projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
> -    tuiAssetsPathProvider('https://taiga-ui.dev/next/assets/taiga-ui/icons'),
Your branch stackblitz

<img width="435" alt="after-stackblitz" src="https://github.com/user-attachments/assets/c32c7f02-9a59-4108-9b46-88c3ff5fb19f">

2024-09-27 12:49 UTC, splincode commented on projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
> -    tuiAssetsPathProvider('https://taiga-ui.dev/next/assets/taiga-ui/icons'),
fixed

2024-09-27 14:28 UTC, mdlufy approved these changes

2024-09-28 08:58 UTC, splincode commented
@nsbarsukov

2024-09-30 08:19 UTC, waterplea approved these changes

2024-09-30 08:57 UTC, nsbarsukov approved these changes

2024-09-30 09:18 UTC, merged