Feature #3417 - Implement tuiDropdownDirectionChange & tuiHintDirectionChange
taiga-family/taiga-ui pull request #9645
Opened 2024-10-30 20:25 UTC by shiv9604

Close #3417

2024-11-06 21:27 UTC, shiv9604 commented on projects/core/directives/hint/hint.directive.ts
> +        this.service.hintDirection$
Thanks for your valuable feedback and clarification! Please check the resolved PR comments and let me know if anything is required.

2024-11-07 11:04 UTC, waterplea requested changes

2024-11-07 11:04 UTC, waterplea commented on projects/core/directives/hint/hint.directive.ts
> +        this.service.hintDirection$
Great! Added a few more comments, after they are addressed this looks good to me, thank you for your contribution!

2024-11-08 16:33 UTC, shiv9604 commented on projects/core/directives/dropdown/dropdown-position-sided.directive.ts
> +    public emitDirection(direction: TuiVerticalDirection): void {
Resolved

2024-11-08 16:33 UTC, shiv9604 commented on projects/core/directives/dropdown/dropdown.directive.ts
> +            directive: TuiDropdownPosition,
Resolved

2024-11-08 16:33 UTC, shiv9604 commented on projects/core/directives/dropdown/dropdown-position.directive.ts
> +    private lastDirection!: TuiVerticalDirection;
Resolved

2024-11-09 09:24 UTC, waterplea commented on projects/core/directives/dropdown/dropdown-position-sided.directive.ts
> +            this.vertical.emitDirection(better);
It should be `this.previous` here

2024-11-09 09:24 UTC, waterplea commented on projects/core/directives/dropdown/dropdown-position.directive.ts
> +        this.emitDirection(better);
It's not always `better`, sometimes it's `previous`, see `if` on the next line.

2024-11-09 09:24 UTC, waterplea commented on projects/legacy/components/input-tag/input-tag.style.less
> +    :host:not(._readonly):not(._disabled):hover .t-textfield-icon ::ng-deep [tuiAppearance][data-appearance='icon']::after {
Weird that this got affected 🤔 You should rollback those style changes. Maybe you need to run `npm i` to update some lint config packages locally?

2024-11-09 09:24 UTC, waterplea commented on projects/core/directives/dropdown/dropdown-position-sided.directive.ts
> +    providers: [tuiAsPositionAccessor(TuiDropdownPositionSided)],
Looks like this was still necessary. Please put it back — I'll investigate myself later how so.

2024-11-22 21:34 UTC, closed without merging